config/routes.rb
Rails.application.routes.draw do

  rutarel = ENV.fetch('RUTA_RELATIVA', 'somosdefensores/siaddhh')
  scope rutarel do 
    devise_scope :usuario do
      get 'sign_out' => 'devise/sessions#destroy'
      get 'salir' => 'devise/sessions#destroy',
        as: :terminar_sesion

      post 'usuarios/iniciar_sesion', to: 'devise/sessions#create'
      get 'usuarios/iniciar_sesion', to: 'devise/sessions#new',
        as: :iniciar_sesion


      # El siguiente para superar mala generación del action en el formulario
      # cuando se monta en sitio diferente a / y se autentica mal (genera 
      # /puntomontaje/puntomontaje/usuarios/sign_in )
      if (Rails.configuration.relative_url_root != '/') 
        ruta = File.join(Rails.configuration.relative_url_root, 
                         'usuarios/sign_in')
        post ruta, to: 'devise/sessions#create'
        get  ruta, to: 'devise/sessions#new'
      end
    end

    devise_for :usuarios, :skip => [:registrations], module: :devise
    as :usuario do
      get 'usuarios/edit' => 'devise/registrations#edit', 
        :as => 'editar_registro_usuario'    
      put 'usuarios/:id' => 'devise/registrations#update', 
        :as => 'registro_usuario'            
    end
    resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' } 

    namespace :admin do
      ab = ::Ability.new
      ab.tablasbasicas.each do |t|
        if (t[0] == "") 
          c = t[1].pluralize
          resources c.to_sym, 
            path_names: { new: 'nueva', edit: 'edita' }
        end
      end
    end


    get '/casos/mapaosm' => 'sivel2_gen/casos#mapaosm'
#    match '/casos.csv' => 'sivel2_gen/casos#index', via: :get, 
#      defaults: { format: :csv }
    root 'sivel2_gen/hogar#index'

  end

  mount Msip::Engine => rutarel, as: 'msip'
  mount Mr519Gen::Engine => rutarel, as: 'mr519_gen'
  mount Heb412Gen::Engine => rutarel, as: 'heb412_gen'
  mount Sivel2Gen::Engine => rutarel, as: 'sivel2_gen'

end

app/views/layouts/application.html.erb
<% content_for :titulo do %>
  <% if defined?(current_usuario) && current_usuario %>
    <%= Msip.titulo %>
  <% else %>
    SIADDHH
  <% end %>
<% end %>

<% content_for :enlace_marca do %>
  <%= sivel2_gen.casos_mapaosm_path %>
<% end %>

<% content_for :menu do %>
  <%= grupo_menus do %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo 'Casos' do %>
        <%= opcion_menu 'Listado', sivel2_gen.casos_path,
          desplegable: true %>
        <%= opcion_menu 'Nuevo Caso', sivel2_gen.new_caso_path,
          desplegable: true %>
        <%= opcion_menu 'Validar casos', sivel2_gen.validarcasos_path,
          desplegable: true %>
        <%= opcion_menu 'Buscar repetidos', sivel2_gen.buscarrepetidos_path,
          desplegable: true %>
        <%= opcion_menu "Casos sobre Open Street Maps", 
          sivel2_gen.casos_mapaosm_path, desplegable: true %>
      <% end %>
      <%= despliega_abajo 'Reportes y conteos' do %>
        <%= opcion_menu 'Listado de víctimas y casos', 
          sivel2_gen.victimas_path,
          desplegable: true %>
        <%= opcion_menu 'Conteo demografía víctimas', 
          sivel2_gen.conteos_personas_path,
          desplegable: true %>
        <%= opcion_menu 'Conteo de victimizaciones individuales', 
          sivel2_gen.conteos_victimizaciones_path,
          desplegable: true %>
        <%= opcion_menu 'Conteo general de víctimas', 
          sivel2_gen.conteos_genvic_path,
          desplegable: true %>
        <%= opcion_menu 'Graficar victimizaciones individuales', 
          sivel2_gen.graficar_victimizaciones_individuales_path,
          'data-turbo' => false,
          desplegable: true %>
        <%= opcion_menu 'Graficar actos individuales', 
          sivel2_gen.graficar_actos_individuales_path,
          'data-turbo' => false,
          desplegable: true %>
        <%= opcion_menu 'Mapa de victimizaciones por departamento', 
          sivel2_gen.mapadepvic_path,
          'data-turbo' => false,
          desplegable: true %>

      <% end %>
    <% end %>
  <% end %>
  <%= grupo_menus :pull => :right do %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo 'Documentos' do %>
        <%= opcion_menu 'Manual', 'https://docs.google.com/document/d/1joHEywmAs7kf1VSEFG_stKKnzEoi73gE1Bjk596bx7Y/edit?usp=sharing',
          desplegable: true %>
        <%= opcion_menu 'Nube', heb412_gen.sisini_path,
          desplegable: true %>
        <% if can? :manage, ::Heb412Gen::Plantillahcm %>
          <%= opcion_menu 'Plantillas para listado en hojas de calculo',
            heb412_gen.plantillashcm_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, ::Heb412Gen::Plantillahcr %>
          <%= opcion_menu 'Plantillas para un registro en hoja de calculo',
            heb412_gen.plantillashcr_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, ::Heb412Gen::Plantilladoc %>
          <%= opcion_menu 'Plantillas para un registro en documento',
            heb412_gen.plantillasdoc_path,
            desplegable: true %>
        <% end %>
      <% end %>
      <%= despliega_abajo 'Administrar' do %>
        <%= opcion_menu 'Clave y tema', main_app.editar_registro_usuario_path,
          desplegable: true %>
        <%= opcion_menu 'Colectivos', msip.orgsociales_path,
          desplegable: true %>
        <% if session[:capturacaso_acordeon] %>
           <%= opcion_menu 'Ficha caso vertical ✓', '/fichacasovertical',
             desplegable: true, id: 'fichacasovertical' 
           %>
        <% else %>
           <%= opcion_menu 'Ficha caso vertical', '/fichacasovertical',
             desplegable: true, id: 'fichacasovertical' 
           %>
        <% end %>
        <% if can? :manage, ::Usuario %>
          <%= opcion_menu 'Usuarios', main_app.usuarios_path,
            desplegable: true %>
        <% end %>

        <% if can? :manage, :tablasbasicas %>
          <%= opcion_menu 'Tablas Básicas', sivel2_gen.tablasbasicas_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, Msip::Respaldo7z %>
          <%= opcion_menu 'Respaldo cifrado', msip.respaldo7z_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, Mr519Gen::Formulario %>
          <%= opcion_menu "Formularios", 
            mr519_gen.formularios_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, Msip::Bitacora %>
          <%= opcion_menu "Bitácoras", msip.bitacoras_path, desplegable: true %>
        <% end %>
        <%= opcion_menu 'Ayuda Control de Acceso', 
          msip.ayuda_controldeacceso_path,
          desplegable: true %>
      <% end %>
      <%= opcion_menu "Salir #{current_usuario.nusuario}", 
        main_app.terminar_sesion_path %>
    <% else %>
      <%= opcion_menu 'Acerca de', sivel2_gen.acercade_path %>
      <% if ENV.fetch('SIADDHH_PUBLICO', '0') == '0' %>
        <%= opcion_menu 'Iniciar Sesión', main_app.iniciar_sesion_path %> 
      <% end %>
    <% end %>
  <% end %>
<% end %>

<% content_for :piedepagina do %>
  <p>
  Sistema de información de 
  <a href="https://github.com/pasosdeJesus/siaddhh">código abierto</a>
  desarrollado por 
    <a href='http://www.pasosdeJesus.org' target='_blank'>Pasos de Jesús</a>.
    2023.
  </span></p>
<% end %>

<%= render template: 'layouts/msip/application' %>